//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.11 at 08:58:22 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://company.com/spring_jsp/webservices/country", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.company.spring_jsp.webservices.country;
